// Module included in the following assemblies:
//
// * security/cert_manager_operator/cert-manager-authenticate-gcp.adoc

:_content-type: PROCEDURE
[id="cert-manager-configure-cloud-credentials-gcp-sts"]
= Preparing cloud credentials for the {cert-manager-operator} with GCP Workload Identity

You can prepare cloud credentials for the {cert-manager-operator} on GCP workload identity by using the `ccoctl` binary.

.Prerequisites

* You must extract and prepare the `ccoctl` binary.

.Procedure

. The {cert-manager-operator} creates the `CredentialsRequest` object in the `openshift-cloud-credential-operator` namespace. Get the role by running the following command:
+
[source,terminal]
----
$ oc get credentialsrequest -n openshift-cloud-credential-operator -o yaml
----
+
.Example output
[source,terminal]
----
output
----

. Annotate the service account by running the following command:
+
[source,terminal]
----
$ oc annotate sa/cert-manager -n cert-manager to-do-value
----

. Get the name of a cert-manager controller pod by running the following command:
+
[source,terminal]
----
$ oc get pods -n cert-manager
----
+
. Example output
[source,terminal
----
NAME                                       READY   STATUS    RESTARTS   AGE
cert-manager-bd7fbb9fc-wvbbt               1/1     Running   0          15m39s
cert-manager-cainjector-56cc5f9868-7g9z7   1/1     Running   0          15m5s
cert-manager-webhook-d4f79d7f7-9dg9w       1/1     Running   0          159s
----

. Get the list of GCP environment variables to check if cloud credentials are updated by running the following command:
+
[source,terminal]
----
$ oc set env -n cert-manager po/<cert-manager_controller_pod_name> --list
----
+
.Example output
[source,terminal]
----
output
----