// Module included in the following assemblies:
//
// * security/cert_manager_operator/cert-manager-authenticate-gcp.adoc

:_content-type: PROCEDURE
[id="cert-manager-configure-cloud-credentials-gcp-sts"]
= Configuring cloud credentials for the {cert-manager-operator} without GCP Workload Identity

You can configure cloud credentials for the {cert-manager-operator} on GCP without workload identity by using the `ccoctl` binary.

.Prerequisites

* You must extract and prepare the `ccoctl` binary.

.Procedure

. The {cert-manager-operator} creates the `CredentialsRequest` object in the `openshift-cloud-credential-operator` namespace.
+
[source,terminal]
----
$ oc get credentialsrequest -n openshift-cloud-credential-operator -o yaml
----

. Get the name of a cert-manager controller pod by running the following command:
+
[source,terminal]
----
$ oc get pods -n cert-manager
----
+
.Example output
[source,terminal]
----
NAME                                       READY   STATUS    RESTARTS   AGE
cert-manager-bd7fbb9fc-wvbbt               1/1     Running   0          15m39s
----

. Get the list of GCP environment variables to check if cloud credentials are updated by running the following command:
+
[source,terminal]
----
$ oc set env -n cert-manager po/<cert-manager_controller_pod_name> --list
----
+
.Example output
[source,terminal]
----
# pods/cert-manager-57f9555c54-4qz47, container cert-manager-controller
# POD_NAMESPACE from field path metadata.namespace
----