// Module included in the following assemblies:
//
// * security/cert_manager_operator/cert-manager-authenticate-gcp.adoc

:_content-type: PROCEDURE
[id="cert-manager-prepare-cloud-credentials-gcp-sts"]
= Preparing cloud credentials for the {cert-manager-operator} with GCP Workload Identity

You can prepare cloud credentials for the {cert-manager-operator} on the GCP Security Token Service (STS) cluster by using the `ccoctl` binary.

.Prerequisites

* You must extract and prepare the `ccoctl` binary.

.Procedure

. Create the `cert-manager` namespace by running the following command:
+
[source,terminal]
----
$ oc create namespace cert-manager
----

. create a directory to store the `CredentialsRequest` custom resource (CR) of the {cert-manager-operator} by running the following command:
+
[source,terminal]
----
$ mkdir credentials-request
----

. Change the directory by running the following command:
+
[source,terminal]
----
$ cd credentials-request
----

. Create a `CredentialsRequest` resource YAML file, for example, `sample-credential-request.yaml`, as follows:
+
[source,yaml]
----
apiVersion: cloudcredential.openshift.io/v1
kind: CredentialsRequest
metadata:
  generation: 1
  labels:
    app: cert-manager
    app.kubernetes.io/component: controller
    app.kubernetes.io/instance: cert-manager
    app.kubernetes.io/name: cert-manager
  name: cert-manager
  namespace: openshift-cloud-credential-operator
spec:
  providerSpec:
    apiVersion: cloudcredential.openshift.io/v1
    kind: GCPProviderSpec
    predefinedRoles:
    - roles/dns.admin
  secretRef:
    name: gcp-credentials
    namespace: cert-manager
  serviceAccountNames:
  - cert-manager
----

. Create a `CredentialsRequest` resource by running the following command:
+
[source,terminal]
----
$ oc create -f sample-credential-request.yaml
----

. Update the subscription object for {cert-manager-operator} by running the following command:
+
[source,terminal]
----
$ oc -n cert-manager-operator patch subscription cert-manager-operator --type='merge' -p '{"spec":{"config":{"env":[{"name":"CLOUD_CREDENTIALS_SECRET_NAME","value":"gcp-credentials"}]}}}'
----

. Verify that the secret is updated by running the following command:
+
[source,terminal]
----
$ oc get deployment cert-manager -n cert-manager -o yaml
----
+
.Example output
[source,terminal]
----
- name: cloud-credentials
        secret:
          defaultMode: 420
          items:
          - key: service_account.json
            path: application_default_credentials.json
          secretName: gcp-credentials
----