// Module included in the following assemblies:
//
// * virt/virtual_machines/virtual_disks/virt-managing-vm-snapshots.adoc

:_mod-docs-content-type: PROCEDURE
[id="virt-restoring-vm-from-snapshot-cli_{context}"]
= Restoring a virtual machine from a snapshot in the CLI

You can restore an existing virtual machine (VM) to a previous configuration by using a VM snapshot. You can only restore from an offline VM snapshot.

.Prerequisites

* Install the {oc-first}.
* Power down the VM you want to restore to a previous state.

.Procedure

. Create a YAML file to define a `VirtualMachineRestore` object that specifies the name of the VM you want to restore and the name of the snapshot to be used as the source.
+
For example:
+
[source,yaml]
----
apiVersion: snapshot.kubevirt.io/v1alpha1
kind: VirtualMachineRestore
metadata:
  name: my-vmrestore
spec:
  target:
    apiGroup: kubevirt.io
    kind: VirtualMachine
    name: my-vm
  virtualMachineSnapshotName: my-vmsnapshot
----
+
where:
+
** `my-vmrestore` is the name of the new `VirtualMachineRestore` object.
** `my-vm` is the name of the target VM you want to restore.
** `my-vmsnapshot` is the name of the `VirtualMachineSnapshot` object to be used as the source.

. Create the `VirtualMachineRestore` resource. The snapshot controller updates the status fields of the `VirtualMachineRestore` object and replaces the existing VM configuration with the snapshot content.
+
[source,terminal]
----
$ oc create -f <my-vmrestore>.yaml
----

.Verification

* Verify that the VM is restored to the previous state represented by the snapshot and that the `status.complete` flag is set to `true`:
+
[source,terminal]
----
$ oc get vmrestore <my-vmrestore>
----
+
.Example output
+
[source, yaml]
----
apiVersion: snapshot.kubevirt.io/v1alpha1
kind: VirtualMachineRestore
metadata:
  creationTimestamp: "2020-09-30T14:46:27Z"
  generation: 5
  name: my-vmrestore
  namespace: default
  ownerReferences:
  - apiVersion: kubevirt.io/v1
    blockOwnerDeletion: true
    controller: true
    kind: VirtualMachine
    name: my-vm
    uid: 355897f3-73a0-4ec4-83d3-3c2df9486f4f
  resourceVersion: "5512"
  selfLink: /apis/snapshot.kubevirt.io/v1alpha1/namespaces/default/virtualmachinerestores/my-vmrestore
  uid: 71c679a8-136e-46b0-b9b5-f57175a6a041
spec:
  target:
    apiGroup: kubevirt.io
    kind: VirtualMachine
    name: my-vm
  virtualMachineSnapshotName: my-vmsnapshot
status:
  complete: true
  conditions:
  - lastProbeTime: null
    lastTransitionTime: "2020-09-30T14:46:28Z"
    reason: Operation complete
    status: "False"
    type: Progressing
  - lastProbeTime: null
    lastTransitionTime: "2020-09-30T14:46:28Z"
    reason: Operation complete
    status: "True"
    type: Ready
  deletedDataVolumes:
  - test-dv1
  restoreTime: "2020-09-30T14:46:28Z"
  restores:
  - dataVolumeName: restore-71c679a8-136e-46b0-b9b5-f57175a6a041-datavolumedisk1
    persistentVolumeClaim: restore-71c679a8-136e-46b0-b9b5-f57175a6a041-datavolumedisk1
    volumeName: datavolumedisk1
    volumeSnapshotName: vmsnapshot-28eedf08-5d6a-42c1-969c-2eda58e2a78d-volume-datavolumedisk1
----
+
[NOTE]
====
If the `Progressing` condition has `status: "True"`, the VM is still being restored.
====
